window.__elonData = {
  contact: {
    id: "elon-musk",
    name: "Elon Musk",
    role: "CEO of Tesla & SpaceX",
    avatar: "https://jmail.world/_next/image?url=%2Fpeople-thumbnails%2Felon-musk.png&w=128&q=75"
  },
  conversation: {
    last: "09/02/14",
    preview: "you or you and talulah, are welcome for breakfast tomorw.",
    msgs: [
      {"id":1,"from":"them","text":"I agree","time":"12:00 PM","date":"Wed, Aug 26, 2009"},
      {"id":2,"from":"them","text":"That was indeed a very enjoyable conversation!  On Sep 23, 2012, at 6:28 PM, \\","time":"12:00 PM","date":"Mon, Sep 24, 2012"},
      {"id":3,"from":"them","text":"Sounds good, will try to make it.","time":"12:00 PM","date":"Tue, Sep 25, 2012"},
      {"id":4,"from":"them","text":"Hopefully the first of many  Sorry for all the typos .Sent from my iPhone","time":"12:00 PM","date":"Tue, Sep 25, 2012"},
      {"id":5,"from":"them","text":"Demis Hassabis  EFTAR100505578 EFTA02006285","time":"12:00 PM","date":"Sat, Sep 29, 2012"},
      {"id":6,"from":"them","text":"SolarCity is just in US major markets right now, which might include NM. Will send them a note.","time":"12:00 PM","date":"Thu, Oct 4, 2012"},
      {"id":7,"from":"them","text":"Leaving either late tonight or tomorrow night.  Will be in Germany Oct 19-21","time":"12:00 PM","date":"Thu, Oct 4, 2012"},
      {"id":8,"from":"them","text":"I have to be back in CA by then","time":"12:00 PM","date":"Thu, Oct 4, 2012"},
      {"id":9,"from":"them","text":"Begin forwarded message:  From: Peter Rive <mailto:>>> Date: October 4, 2012, 6:35:03 PM EDT To: Elo","time":"12:00 PM","date":"Fri, Oct 5, 2012"},
      {"id":10,"from":"them","text":"Late Nov is a possibility. Between now and then, I have to complete the Dragon mission, get Tesla to","time":"12:00 PM","date":"Thu, Oct 11, 2012"},
      {"id":11,"from":"them","text":"The world needs more romance.  I will be in NY around mid Nov for some media events, but not before.","time":"12:00 PM","date":"Fri, Oct 19, 2012"},
      {"id":12,"from":"them","text":"Let's aim for Dec 28, 29 or 30.","time":"12:00 PM","date":"Fri, Nov 2, 2012"},
      {"id":13,"from":"them","text":"What's a good time to come over between Dec 23 and 30?  On Oct 19, 2012, at 4:19 PM, \\","time":"12:00 PM","date":"Fri, Nov 2, 2012"},
      {"id":14,"from":"them","text":"Probably just Talulah and me. What day/night will be the wildest party on our island?","time":"12:00 PM","date":"Sun, Nov 25, 2012"},
      {"id":15,"from":"them","text":"Do you have any parties planned? I've been working to the edge of sanity this year and so, once my k","time":"12:00 PM","date":"Tue, Dec 25, 2012"},
      {"id":16,"from":"them","text":"Unfortunately, we are not on St Bart's tomorrow. Back afternoon of the 30th=","time":"12:00 PM","date":"Fri, Dec 28, 2012"},
      {"id":17,"from":"them","text":"Do you want to join us (and some others) for drinks on the 30th around 10 o= 11?  On Dec 28, 2012, a","time":"12:00 PM","date":"Fri, Dec 28, 2012"},
      {"id":18,"from":"them","text":"Ok, we could perhaps get together for lunch on the 31st.  On Dec 29, 2012, at 11:07 AM, \\","time":"12:00 PM","date":"Sat, Dec 29, 2012"},
      {"id":19,"from":"them","text":"Logistics won't work this time around.","time":"12:00 PM","date":"Wed, Jan 2, 2013"},
      {"id":20,"from":"them","text":"Could meet for lunch. Will be with Talulah and her friend Debs.","time":"12:00 PM","date":"Thu, Jan 3, 2013"},
      {"id":21,"from":"them","text":"Anyplace here that you like to have lunch?  On Jan 3, 2013, at 9:02 PM, \\","time":"12:00 PM","date":"Fri, Jan 4, 2013"},
      {"id":22,"from":"them","text":"I've been ill all night. Not sure if it is food poisoning or a bug. Either =ay, I'm not well enough ","time":"12:00 PM","date":"Tue, Jan 29, 2013"},
      {"id":23,"from":"them","text":"I will be speaking at TED, but not there for very long.  If you would like to talk, it would be best","time":"12:00 PM","date":"Tue, Feb 19, 2013"},
      {"id":24,"from":"them","text":"Up to you","time":"12:00 PM","date":"Thu, Feb 21, 2013"},
      {"id":25,"from":"them","text":"Yes, the airport is about 100 meters away from SpaceX HQ.  Are you coming from far away? Not really ","time":"12:00 PM","date":"Sat, Feb 23, 2013"},
      {"id":26,"from":"them","text":"It is 3am in California and I'm still working on Tesla and SpaceX email. W=lI hit the sack shortly, ","time":"12:00 PM","date":"Mon, Mar 4, 2013"},
      {"id":27,"from":"them","text":"Thanks. Now I need to focus on Tesla. Hopefully will have that sorted out in a few months.","time":"12:00 PM","date":"Mon, Mar 4, 2013"},
      {"id":28,"from":"them","text":"Normally I would agree, as I have found that my total daily productivity is optimal at around 6 to 6","time":"12:00 PM","date":"Wed, Mar 6, 2013"},
      {"id":29,"from":"them","text":"Better, yes. Workload, no.","time":"12:00 PM","date":"Thu, Mar 21, 2013"},
      {"id":30,"from":"them","text":"No firm plans","time":"12:00 PM","date":"Wed, Apr 10, 2013"},
      {"id":31,"from":"them","text":"Thanks. I might be in town for the Time 100. Not sure yet.  On Apr 10, 2013, at 4:17 PM, \\","time":"12:00 PM","date":"Thu, Apr 11, 2013"},
      {"id":32,"from":"them","text":"no","time":"12:00 PM","date":"Mon, Apr 15, 2013"},
      {"id":33,"from":"them","text":"I was only there for a few hours and then flew to the Bay Area  On May 1, 2013, at 2:22 PM, \\","time":"12:00 PM","date":"Fri, May 17, 2013"},
      {"id":34,"from":"them","text":"Due to the high volume of unsolicited email, my address has changed. Please send me a text or call t","time":"12:00 PM","date":"Wed, Sep 11, 2013"},
      {"id":35,"from":"them","text":"Yes","time":"12:00 PM","date":"Sat, Nov 23, 2013"},
      {"id":36,"from":"them","text":"Is there a day/night that you would particularly recommend within those dates?  On Dec 13, 2013, at ","time":"12:00 PM","date":"Sat, Dec 14, 2013"},
      {"id":37,"from":"them","text":"I will send heli for you  Sorry for all the typos .Sent from my iPhone","time":"12:00 PM","date":"Sat, Dec 14, 2013"},
      {"id":38,"from":"me","text":"Anytime I will be there 28-7th  Sorry for all the typos .Sent from my iPhone","time":"12:00 PM","date":"Sat, Dec 14, 2013"},
      {"id":39,"from":"them","text":"Will be in the BVI/St Bart's area over the holidays. Is there a good time to visit?","time":"12:00 PM","date":"Sat, Dec 14, 2013"},
      {"id":40,"from":"them","text":"Ok, probably the 1st then.","time":"12:00 PM","date":"Sun, Dec 15, 2013"},
      {"id":41,"from":"them","text":"Actually, I could fly back early on the 3rd. We will be in St Bart's. When should we head to your is","time":"12:00 PM","date":"Wed, Dec 25, 2013"},
      {"id":42,"from":"them","text":"I need to fly back to LA on the night of the 2nd, so w  On Dec 25, 2013, at 6:34 AM, \\","time":"12:00 PM","date":"Wed, Dec 25, 2013"},
      {"id":43,"from":"them","text":"Did we need to organize Elon to your island on Jan 2nd?  Begin forwarded message:  From: Elon Musk <","time":"12:00 PM","date":"Mon, Dec 30, 2013"},
      {"id":44,"from":"them","text":"Just a reminder Elon Musk was asking about coming to your island on Jan. 2....","time":"12:00 PM","date":"Mon, Jan 6, 2014"},
      {"id":45,"from":"them","text":"Ok","time":"12:00 PM","date":"Tue, Sep 2, 2014"},
      {"id":46,"from":"them","text":"you or you and talulah, are welcome for breakfast tomorw.","time":"12:00 PM","date":"Tue, Sep 2, 2014"}
    ]
  }
};
